{
  "openapi" : "3.0.3",
  "info" : {
    "title" : "Zoom API",
    "description" : "The Zoom API allows developers to access information from Zoom. You can use this API to build private services or public applications on the [Zoom App Marketplace](http://marketplace.zoom.us). To learn how to get your credentials and create private/public applications, read our [Authorization Guide](https://marketplace.zoom.us/docs/guides/authorization/credentials).\nAll endpoints are available via `https` and are located at `api.zoom.us/v2/`.\n\nFor instance you can list al[...]",
    "contact" : { },
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "https://api.zoom.us/v2"
  } ],
  "tags" : [ {
    "name" : "accounts"
  }, {
    "name" : "{account Id}"
  }, {
    "name" : "phone"
  }, {
    "name" : "sip trunk/trunks"
  }, {
    "name" : "settings"
  }, {
    "name" : "virtual backgrounds"
  }, {
    "name" : "billing"
  }, {
    "name" : "invoices"
  }, {
    "name" : "plans"
  }, {
    "name" : "base"
  }, {
    "name" : "addons"
  }, {
    "name" : "lock settings"
  }, {
    "name" : "sip trunk"
  }, {
    "name" : "numbers"
  }, {
    "name" : "trunks"
  }, {
    "name" : "callout countries"
  }, {
    "name" : "internal numbers"
  }, {
    "name" : "tracking fields"
  }, {
    "name" : "{field Id}"
  }, {
    "name" : "users"
  }, {
    "name" : "{user Id}"
  }, {
    "name" : "meetings"
  }, {
    "name" : "assistants"
  }, {
    "name" : "schedulers"
  }, {
    "name" : "settings1"
  }, {
    "name" : "virtual backgrounds1"
  }, {
    "name" : "tsp"
  }, {
    "name" : "{tsp Id}"
  }, {
    "name" : "token"
  }, {
    "name" : "webinars"
  }, {
    "name" : "meetings/{meeting Id}"
  }, {
    "name" : "registrants"
  }, {
    "name" : "questions"
  }, {
    "name" : "past meetings"
  }, {
    "name" : "{meeting UUID}"
  }, {
    "name" : "{meeting Id}"
  }, {
    "name" : "metrics"
  }, {
    "name" : "meetings1"
  }, {
    "name" : "{meeting Id}1"
  }, {
    "name" : "participants"
  }, {
    "name" : "webinars1"
  }, {
    "name" : "{webinar Id}"
  }, {
    "name" : "participants1"
  }, {
    "name" : "client"
  }, {
    "name" : "feedback"
  }, {
    "name" : "report"
  }, {
    "name" : "users1"
  }, {
    "name" : "meetings/{meeting Id}1"
  }, {
    "name" : "webinars/{webinar Id}"
  }, {
    "name" : "webinars/{webinar Id}1"
  }, {
    "name" : "panelists"
  }, {
    "name" : "registrants1"
  }, {
    "name" : "questions1"
  }, {
    "name" : "{registrant Id}"
  }, {
    "name" : "polls"
  }, {
    "name" : "{poll Id}"
  }, {
    "name" : "past webinars"
  }, {
    "name" : "{webinar Id}1"
  } ],
  "paths" : {
    "/accounts" : {
      "get" : {
        "tags" : [ "accounts" ],
        "summary" : "List sub accounts",
        "description" : "List all the sub accounts that have been created by a master account.<br><br>Zoom allows only [approved partners](https://marketplace.zoom.us/docs/api-reference/master-account-apis) to use master APIs and manage sub accounts. Email the partner programs team at **partner-success@zoom.us** for more details.\n\n<br>**Prerequisites:**<br>\n* Pro or a higher paid account with master account option enabled. <br>\n\n**Scope**: `account:read:admin`\n<br>**[Rate Limit Label](http[...]",
        "operationId" : "listSubAccounts"
      },
      "post" : {
        "tags" : [ "accounts" ],
        "summary" : "Create a sub account",
        "description" : "Create a sub account under a master account. Your account must be a master account in order to create sub accounts. \n<br><br>Zoom allows only [approved partners](https://marketplace.zoom.us/docs/api-reference/master-account-apis) to use master APIs and manage sub accounts. Email the partner programs team at partner-success@zoom.us. for more details. Please note that the created account user will receive a confirmation email.<br><br>\n<br>\n**Prerequisites:**<br>\n* Pro [...]",
        "operationId" : "createASubAccount"
      }
    },
    "/accounts/{accountId}" : {
      "get" : {
        "tags" : [ "accounts", "{account Id}" ],
        "summary" : "Get sub account details",
        "description" : "Get details of a sub account that is listed under a master account. Your account must be a master account in order to retrieve sub accounts' details. Zoom allows only [approved partners](https://marketplace.zoom.us/docs/api-reference/master-account-apis) to use master APIs and create sub accounts. Email the partner programs team at **partner-success@zoom.us** for more details.\n\n**Prerequisites:**\n* Pro or a higher paid account with master account option enabled. <br>\[...]",
        "operationId" : "getSubAccountDetails"
      },
      "delete" : {
        "tags" : [ "accounts", "{account Id}" ],
        "summary" : "Disassociate a sub account",
        "description" : "Disassociate a sub account from its master account. This will leave the sub account intact but it will no longer be associated with the master account.<br>  \n\n**Prerequisites:**\n* Pro or a higher paid account with master account option enabled. <br>\n* The account making this API request must be a [master account](https://marketplace.zoom.us/docs/api-reference/master-account-apis).<br><br>\n\n\n**Scope**: `account:write:admin`<br>\n**[Rate Limit Label](https://marketp[...]",
        "operationId" : "disassociateASubAccount"
      }
    },
    "/accounts/{accountId}/billing" : {
      "get" : {
        "tags" : [ "accounts", "{account Id}", "billing" ],
        "summary" : "Get billing information",
        "description" : "Get [billing information](https://support.zoom.us/hc/en-us/articles/201363263-About-Billing) of a sub account.<br><br>Only master accounts can use this API. Zoom allows only [approved partners](https://marketplace.zoom.us/docs/api-reference/master-account-apis) to use master APIs and manage sub accounts' billing information. Email the partner programs team at **partner-success@zoom.us** for more details.<br>\n\n**Prerequisites:**\n* Pro or a higher paid account with mast[...]",
        "operationId" : "getBillingInformation"
      },
      "patch" : {
        "tags" : [ "accounts", "{account Id}", "billing" ],
        "summary" : "Update billing information",
        "description" : "Update [billing information](https://support.zoom.us/hc/en-us/articles/201363263-About-Billing) of a sub account.<br><br>\nThis API can only be used by master accounts that pay all billiing charges of their associated sub accounts. Zoom allows only [approved partners](https://marketplace.zoom.us/docs/api-reference/master-account-apis) to use master APIs and manage sub accounts' billing information. Email the partner programs team at **partner-success@zoom.us** for more d[...]",
        "operationId" : "updateBillingInformation"
      }
    },
    "/accounts/{accountId}/billing/invoices" : {
      "get" : {
        "tags" : [ "accounts", "{account Id}", "billing", "invoices" ],
        "summary" : "List billing invoices",
        "description" : "List [invoices](https://support.zoom.us/hc/en-us/articles/207276556-Viewing-your-invoice-history#h_6710542f-23cc-4059-9cc7-ff02bec7314e) of a Zoom account.\n\nTo list a regular Zoom account's invoices or a master account's invoices, provide `me` as the value of the `accountId` path parameter. To list a sub account's invoices, provide the account ID of the sub account in the `accountId` path parameter. \n\n**Prerequisites:**\n* Account must be enrolled in Pro or a higher [...]",
        "operationId" : "listBillingInvoices"
      }
    },
    "/accounts/{accountId}/billing/invoices/{invoiceId}" : {
      "get" : {
        "tags" : [ "accounts", "{account Id}", "billing", "invoices" ],
        "summary" : "Get invoice details",
        "description" : "Get detailed information about a specific [invoice](https://support.zoom.us/hc/en-us/articles/207276556-Viewing-your-invoice-history#h_6710542f-23cc-4059-9cc7-ff02bec7314e). <br>To retrieve a regular Zoom account's invoice details or a master account's invoice details, provide `me` as the value of `accountId` path parameter. To list a sub account's invoice details, provide the account ID of the sub account in the `accountId` path parameter. \n\n**Prerequisites:**\n* Acco[...]",
        "operationId" : "getInvoiceDetails"
      }
    },
    "/accounts/{accountId}/lock_settings" : {
      "get" : {
        "tags" : [ "accounts", "{account Id}", "lock settings" ],
        "summary" : "Get locked settings",
        "description" : "[Account Locked Settings](https://support.zoom.us/hc/en-us/articles/115005269866) allow you turn settings on or off for all users in your account. No user except the account admin or account owner can change these settings. With lock settings, you force the settings on for all users.\nUse this API to retrieve an account's locked settings. \n\n**Note:** This API can be used by Zoom Accounts that are on a Pro or a higher plan as well accounts that have master and sub accou[...]",
        "operationId" : "getLockedSettings"
      },
      "patch" : {
        "tags" : [ "accounts", "{account Id}", "lock settings" ],
        "summary" : "Update locked settings",
        "description" : "[Account Locked Settings](https://support.zoom.us/hc/en-us/articles/115005269866) allow you turn settings on or off for all users in your account. No user except the account admin or account owner can change these settings. With lock settings, you force the settings on for all users. Use this API to update an account's locked settings.\n\n**Note:** This API can be used by Zoom Accounts that are on a Pro or a higher plan as well accounts that have master and sub accounts [...]",
        "operationId" : "updateLockedSettings"
      }
    },
    "/accounts/{accountId}/managed_domains" : {
      "get" : {
        "tags" : [ "accounts", "{account Id}" ],
        "summary" : "Get managed domains",
        "description" : "Get a sub account's [managed domains](https://support.zoom.us/hc/en-us/articles/203395207-What-is-Managed-Domain-).<br><br>\n\n**Note:** This API can be used by Zoom Accounts that are on a Pro or a higher plan as well accounts that have master and sub accounts options enabled. <br><br>\nTo get managed domains of the master account, provide `me` as the value for accountId in the path parameter. Provide the sub account's Account ID as the value of accountId path parameter [...]",
        "operationId" : "getManagedDomains"
      }
    },
    "/accounts/{accountId}/options" : {
      "patch" : {
        "tags" : [ "accounts", "{account Id}" ],
        "summary" : "Update options",
        "description" : "Update a sub account's options under the master account.<br> <aside>Your account must be a master account in order to update the options for sub accounts. Zoom only assigns this privilege to trusted partners. </aside>\n\n**Prerequisites:**\n* Pro or a higher paid account with master account option enabled.\n* The account making this API request must be a [master account](https://marketplace.zoom.us/docs/api-reference/master-account-apis).<br><br>\n\n**Scope**: `account:w[...]",
        "operationId" : "updateOptions"
      }
    },
    "/accounts/{accountId}/owner" : {
      "put" : {
        "tags" : [ "accounts", "{account Id}" ],
        "summary" : "Update the account owner",
        "description" : "The current account owner can [change the owner of an account](https://support.zoom.us/hc/en-us/articles/115005686983-Change-Account-Owner) to another user on the same account.<br> Use this API to change the owner of a sub account.\n \n**Prerequisites**: <br>\n* Account owner or admin permissions of an account.\n* The account making this API request must be on a pro or a hiigher plan with [master account](https://marketplace.zoom.us/docs/api-reference/master-account-apis[...]",
        "operationId" : "updateTheAccountOwner"
      }
    },
    "/accounts/{accountId}/phone/settings" : {
      "patch" : {
        "tags" : [ "accounts", "{account Id}", "phone" ],
        "summary" : "Update BYOC settings",
        "description" : "Only [master account owners](https://marketplace.zoom.us/docs/api-reference/master-account-apis) can use this API to enable BYOC(Bring your own carrier) option for a sub account.<br>\n\n**Scope**:<br>\n* `phone:master` <br>\n\n**Prerequisites**: <br>\n* Business or enterprise Account.<br>",
        "operationId" : "updateByocSettings"
      }
    },
    "/accounts/{accountId}/phone/setup" : {
      "post" : {
        "tags" : [ "accounts", "{account Id}", "phone" ],
        "summary" : "Set up a Zoom Phone account",
        "description" : "After assigning a Zoom phone license to an account, an admin or account owner can proceed with the [initial Zoom phone set up](https://support.zoom.us/hc/en-us/articles/360001297663-Getting-started-with-Zoom-Phone-admin-#h_5ae26a3a-290c-4a8d-b3b0-6384ed267b13) using this API.\n\n**Scope**:<br>\n* `phone:write:admin` `phone:write`\n\n**Prerequisites**: <br>\n* Pro or a higher paid account with master account option enabled.\n\n<br>**[Rate Limit Label](https://marketplace.[...]",
        "operationId" : "setUpAZoomPhoneAccount"
      }
    },
    "/accounts/{accountId}/phone/sip_trunk/trunks" : {
      "post" : {
        "tags" : [ "accounts", "{account Id}", "phone", "sip trunk/trunks" ],
        "summary" : "Assign SIP trunks",
        "description" : "Using this API, a [master account](https://marketplace.zoom.us/docs/api-reference/master-account-apis) owner can assign SIP trunk(s) to a sub account.<br>\n\n**Scope**:<br>\n* `phone:master` <br>\n\n**Prerequisites**:<br>\n* Business or enterprise Account.<br>\n<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n\n",
        "operationId" : "assignSipTrunks"
      }
    },
    "/accounts/{accountId}/phone/sip_trunk/trunks/{sipTrunkId}" : {
      "patch" : {
        "tags" : [ "accounts", "{account Id}", "phone", "sip trunk/trunks" ],
        "summary" : "Update SIP trunk details",
        "description" : "Update details of a SIP trunk that is assigned to a sub account.<br>\n\n**Scope**:<br>\n* `phone:master` <br>\n\n**Prerequisites**:<br>\nBusiness or Enterprise Account.<br>\n<br>**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n\n",
        "operationId" : "updateSipTrunkDetails"
      }
    },
    "/accounts/{accountId}/plans" : {
      "get" : {
        "tags" : [ "accounts", "{account Id}", "plans" ],
        "summary" : "Get plan Information",
        "description" : "Get plan information of a sub account that is managed by a master account. <br><br>This API can only be used by master accounts that pay all billiing charges of their associated Pro or higher sub accounts. Zoom allows only [approved partners](https://marketplace.zoom.us/docs/api-reference/master-account-apis) to use master APIs and manage sub accounts' billing information. Email the partner programs team at **partner-success@zoom.us** for more details.<br><br>\n**Scopes:[...]",
        "operationId" : "getPlanInformation"
      },
      "post" : {
        "tags" : [ "accounts", "{account Id}", "plans" ],
        "summary" : "Subscribe plans",
        "description" : "Subscribe a sub account to a Zoom plan using your master account. This API can only be used by master accounts that pay all billiing charges of their associated Pro or higher sub accounts. Zoom allows only [approved partners](https://marketplace.zoom.us/docs/api-reference/master-account-apis) to use master APIs and manage sub accounts' subscriptions. Email the partner programs team at **partner-success@zoom.us** for more details.<br><br>\n**Scopes**: `billing:master`<br>[...]",
        "operationId" : "subscribePlans"
      }
    },
    "/accounts/{accountId}/plans/addons" : {
      "put" : {
        "tags" : [ "accounts", "{account Id}", "plans", "addons" ],
        "summary" : "Update an additional plan",
        "description" : "Update an additional plan for a sub account.\n\nThis API can only be used by master accounts that pay all billiing charges of their associated Pro or higher sub accounts. Zoom allows only [approved partners](https://marketplace.zoom.us/docs/api-reference/master-account-apis) to use master APIs and manage sub accounts' subscriptions. Email the partner programs team at **partner-success@zoom.us** for more details.<br><br>\n<br>**Prerequisites:**<br>\n* Pro or a higher plan[...]",
        "operationId" : "updateAnAdditionalPlan"
      },
      "post" : {
        "tags" : [ "accounts", "{account Id}", "plans", "addons" ],
        "summary" : "Subscribe additional plan",
        "description" : "Subscribe a sub account to a Zoom addon plan. This API can only be used by master accounts that pay all billiing charges of their associated Pro or higher sub accounts. Zoom allows only [approved partners](https://marketplace.zoom.us/docs/api-reference/master-account-apis) to use master APIs and manage sub accounts' subscriptions. Email the partner programs team at **partner-success@zoom.us** for more details.<br><br>\n<br>**Prerequisites:**<br>\n* Pro or a higher plan w[...]",
        "operationId" : "subscribeAdditionalPlan"
      }
    },
    "/accounts/{accountId}/plans/addons/status" : {
      "patch" : {
        "tags" : [ "accounts", "{account Id}", "plans", "addons" ],
        "summary" : "Cancel additional plans",
        "description" : "[Cancel additional plan](https://support.zoom.us/hc/en-us/articles/203634215-How-Do-I-Cancel-My-Subscription-) of a sub account. The cancellation does not provide refund for the current subscription. The service remains active for the current session.\n\nThis API can only be used by master accounts that pay all billiing charges of their associated Pro or higher sub accounts. Zoom allows only [approved partners](https://marketplace.zoom.us/docs/api-reference/master-accoun[...]",
        "operationId" : "cancelAdditionalPlans"
      }
    },
    "/accounts/{accountId}/plans/base" : {
      "put" : {
        "tags" : [ "accounts", "{account Id}", "plans", "base" ],
        "summary" : "Update a base plan",
        "description" : "Update a base plan of a sub account. \n\nThis API can only be used by master accounts that pay all billiing charges of their associated Pro or higher sub accounts. Zoom allows only [approved partners](https://marketplace.zoom.us/docs/api-reference/master-account-apis) to use master APIs and manage sub accounts' subscriptions. Email the partner programs team at **partner-success@zoom.us** for more details.<br><br>\n**Scopes:** `billing:master`<br><br>\n**[Rate Limit Label[...]",
        "operationId" : "updateABasePlan"
      }
    },
    "/accounts/{accountId}/plans/base/status" : {
      "patch" : {
        "tags" : [ "accounts", "{account Id}", "plans", "base" ],
        "summary" : "Cancel a base plan",
        "description" : "[Cancel a base plan](https://support.zoom.us/hc/en-us/articles/203634215-How-Do-I-Cancel-My-Subscription-) for a sub account.\n\nThis API can only be used by master accounts that pay all billiing charges of their associated Pro or higher sub accounts. Zoom allows only [approved partners](https://marketplace.zoom.us/docs/api-reference/master-account-apis) to use master APIs and manage sub accounts' subscriptions. Email the partner programs team at **partner-success@zoom.u[...]",
        "operationId" : "cancelABasePlan"
      }
    },
    "/accounts/{accountId}/plans/usage" : {
      "get" : {
        "tags" : [ "accounts", "{account Id}", "plans" ],
        "summary" : "Get plan usage",
        "description" : "Get information on usage of [plans](https://marketplace.zoom.us/docs/api-reference/other-references/plans) of an account. This API supports regular accounts as well as master and sub accounts. To get plan usage of a regular account, use the `account:read:admin` scope and provide “me” as the value of the  `accountId` path parameter.To get plan usage of a master account, provide the keyword \"me\" as the value of the `accountId` path parameter and use the `billing:master` [...]",
        "operationId" : "getPlanUsage"
      }
    },
    "/accounts/{accountId}/recordings" : {
      "get" : {
        "tags" : [ "accounts", "{account Id}" ],
        "summary" : "List recordings of an account",
        "description" : "List [Cloud Recordings](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording) available on an Account.\n\n> To access a password protected cloud recording, add an \"access_token\" parameter to the download URL and provide [JWT](https://marketplace.zoom.us/docs/guides/getting-started/app-types/create-jwt-app) as the value of the \"access_token\".\n<br>\n**Prerequisites**:<br>\n* A Pro or a higher paid plan with Cloud Recording option enabled.<br>\n**Scopes*[...]",
        "operationId" : "listRecordingsOfAnAccount"
      }
    },
    "/accounts/{accountId}/settings" : {
      "get" : {
        "tags" : [ "accounts", "{account Id}", "settings" ],
        "summary" : "Get settings",
        "description" : "Get the settings of an account.<br>\nTo get the settings of a master account, use `me` as the value for the `accountId` path parameter.<br><br>\n **Prerequisites**:\n * The account must be a paid account.<br>\n**Scopes**: `account:read:admin`\n<br> \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
        "operationId" : "getSettings"
      },
      "patch" : {
        "tags" : [ "accounts", "{account Id}", "settings" ],
        "summary" : "Update settings",
        "description" : "Update the settings of a sub account that is under a master account.<br> To update the settings of the master account, use `me` as the value of the `accountId` path parameter.<br><br>\n**Prerequisites**:\n * The sub account must be a paid account.<br>\n**Scopes**: `account:write:admin`\n<br>\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
        "operationId" : "updateSettings"
      }
    },
    "/accounts/{accountId}/settings/virtual_backgrounds" : {
      "post" : {
        "tags" : [ "accounts", "{account Id}", "settings", "virtual backgrounds" ],
        "summary" : "Upload virtual background files",
        "description" : "Use this API to [upload virtual background files](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background#h_01EJF3YFEWGT8YA0ZJ079JEDQE) for all users on the account to use. \n\n\n**Prerequisites:**<br>\n* Virtual background feature must be [enabled](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background#h_2ef28080-fce9-4ac2-b567-dc958afab1b7) on the account.\n<br> **Scope:** `account:write:admin`<br><br>\n**[Rate Limit Label](https://market[...]",
        "operationId" : "uploadVirtualBackgroundFiles"
      },
      "delete" : {
        "tags" : [ "accounts", "{account Id}", "settings", "virtual backgrounds" ],
        "summary" : "Delete virtual background files",
        "description" : "Delete existing virtual background file(s) from an account. \n\n**Prerequisites:**<br>\n* Virtual background feature must be [enabled](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background#h_2ef28080-fce9-4ac2-b567-dc958afab1b7) on the account.\n<br> **Scope:** `account:write:admin`<br> <br> \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n\n",
        "operationId" : "deleteVirtualBackgroundFiles"
      }
    },
    "/accounts/{accountId}/sip_trunk/callout_countries" : {
      "get" : {
        "tags" : [ "accounts", "{account Id}", "sip trunk", "callout countries" ],
        "summary" : "List internal call-out countries",
        "description" : "Retrieve the list of internal [call-out](https://support.zoom.us/hc/en-us/articles/200942859-How-To-Use-Telephone-Call-Out-) countries of a master account or a sub account. To list call-out enabled countries of a sub account, provide the account ID of the sub account in the `accountId` path parameter. To list call-out enabled countries of a master account, provide `me` as the value of the `accountId` path parameter.\n<br><b>Prerequisites:</b><br>\n* The account making th[...]",
        "operationId" : "listInternalCallOutCountries"
      },
      "post" : {
        "tags" : [ "accounts", "{account Id}", "sip trunk", "callout countries" ],
        "summary" : "Add internal call-out countries",
        "description" : "Specify the list of [call-out](https://support.zoom.us/hc/en-us/articles/200942859-How-To-Use-Telephone-Call-Out-) countries for a master account or a sub account. To add call-out enabled countries to a sub account, provide the account ID of the sub account in the `accountId` path parameter. To add call-out enabled countries to a master account, provide `me` as the value of the `accountId` path parameter.\n<br><b>Prerequisites:</b><br>\n* The account making this API requ[...]",
        "operationId" : "addInternalCallOutCountries"
      }
    },
    "/accounts/{accountId}/sip_trunk/callout_countries/{countryId}" : {
      "delete" : {
        "tags" : [ "accounts", "{account Id}", "sip trunk", "callout countries" ],
        "summary" : "Delete internal call-out country",
        "description" : "Delete a previously assigned [call-out](https://support.zoom.us/hc/en-us/articles/200942859-How-To-Use-Telephone-Call-Out-) country from a master account or a sub account. To remove call-out country from a sub account, provide the account ID of the sub account in the `accountId` path parameter. To remove call-out country from a master account, provide `me` as the value of the `accountId` path parameter.\n<br><b>Prerequisites:</b><br>\n* The account making this API reques[...]",
        "operationId" : "deleteInternalCallOutCountry"
      }
    },
    "/accounts/{accountId}/sip_trunk/internal_numbers" : {
      "get" : {
        "tags" : [ "accounts", "{account Id}", "sip trunk", "internal numbers" ],
        "summary" : "List internal numbers",
        "description" : "This API allows a master account with SIP Connected Audio plan to list internal phone numbers (i.e., numbers that are not provided by Zoom but are owned by the organization consuming the API) assigned to a master account or a sub account.<br><br>To list internal numbers of a sub account, provide the account ID of the sub account in the `accountId` path parameter. To list internal numbers of a  master account, provide `me` as the value of the `accountId` path parameter.\n[...]",
        "operationId" : "listInternalNumbers"
      },
      "post" : {
        "tags" : [ "accounts", "{account Id}", "sip trunk", "internal numbers" ],
        "summary" : "Add internal numbers",
        "description" : "This API allows a master account with SIP Connected Audio plan to assign internal phone numbers (i.e., numbers that are not provided by Zoom but are owned by the organization consuming the API) to a master account or a sub account.<br><br>To add internal numbers to a sub account, provide the account ID of the sub account in the `accountId` path parameter. To add internal numbers to a master account, provide `me` as the value of the `accountId` path parameter.\n<br><b>Pre[...]",
        "operationId" : "addInternalNumbers"
      }
    },
    "/accounts/{accountId}/sip_trunk/internal_numbers/{numberId}" : {
      "delete" : {
        "tags" : [ "accounts", "{account Id}", "sip trunk", "internal numbers" ],
        "summary" : "Delete an internal number",
        "description" : "This API allows a master account with SIP Connected Audio plan to delete a previously assigned internal phone number from a master account or a sub account.<br><br>To delete an internal number from a sub account, provide the account ID of the sub account in the `accountId` path parameter. To delete an internal number from a master account, provide `me` as the value of the `accountId` path parameter.\n<br><b>Prerequisites:</b><br>\n* The account making this API request mu[...]",
        "operationId" : "deleteAnInternalNumber"
      }
    },
    "/accounts/{accountId}/sip_trunk/numbers" : {
      "post" : {
        "tags" : [ "accounts", "{account Id}", "sip trunk", "numbers" ],
        "summary" : "Assign numbers",
        "description" : "With SIP-connected audio, Zoom establishes a SIP trunk (a network connection specifically designed to make and deliver phone calls) over a direct and private connection between the customer’s network and the Zoom cloud. Meeting participants that dial into a meeting or have the meeting call them, and are On-Net from the perspective of the customers' IP telephony network, will be connected over this trunk rather than over the PSTN. <br><br>Use this API to assign internal n[...]",
        "operationId" : "assignNumbers"
      },
      "delete" : {
        "tags" : [ "accounts", "{account Id}", "sip trunk", "numbers" ],
        "summary" : "Delete all numbers",
        "description" : "With SIP-connected audio, Zoom establishes a SIP trunk (a network connection specifically designed to make and deliver phone calls) over a direct and private connection between the customer’s network and the Zoom cloud. Meeting participants that dial into a meeting or have the meeting call them, and are On-Net from the perspective of the customers' IP telephony network, will be connected over this trunk rather than over the PSTN. <br><br>Use this API to delete all intern[...]",
        "operationId" : "deleteAllNumbers"
      }
    },
    "/accounts/{accountId}/sip_trunk/settings" : {
      "patch" : {
        "tags" : [ "accounts", "{account Id}", "sip trunk" ],
        "summary" : "Assign SIP trunk configuration",
        "description" : "With SIP-connected audio, Zoom establishes a SIP trunk (a network connection specifically designed to make and deliver phone calls) over a direct and private connection between the customer’s network and the Zoom cloud. Meeting participants that dial into a meeting or have the meeting call them, and are On-Net from the perspective of the customers' IP telephony network, will be connected over this trunk rather than over the PSTN. <br><br> Using this API, a master account[...]",
        "operationId" : "assignSipTrunkConfiguration"
      }
    },
    "/accounts/{accountId}/sip_trunk/trunks" : {
      "get" : {
        "tags" : [ "accounts", "{account Id}", "sip trunk", "trunks" ],
        "summary" : "List SIP trunks",
        "description" : "With SIP-connected audio, Zoom establishes a SIP trunk (a network connection specifically designed to make and deliver phone calls) over a direct and private connection between the customer’s network and the Zoom cloud. Meeting participants that dial into a meeting or have the meeting call them, and are On-Net from the perspective of the customers’ IP telephony network, will be connected over this trunk rather than over the PSTN.<br><br>\nUse this API to list all the SIP[...]",
        "operationId" : "listSipTrunks"
      },
      "post" : {
        "tags" : [ "accounts", "{account Id}", "sip trunk", "trunks" ],
        "summary" : "Assign SIP trunks",
        "description" : "With SIP-connected audio, Zoom establishes a SIP trunk (a network connection specifically designed to make and deliver phone calls) over a direct and private connection between the customer’s network and the Zoom cloud. Meeting participants that dial into a meeting or have the meeting call them, and are On-Net from the perspective of the customers’ IP telephony network, will be connected over this trunk rather than over the PSTN.<br><br>Use this API to assign SIP trunk(s[...]",
        "operationId" : "assignSipTrunks1"
      }
    },
    "/accounts/{accountId}/sip_trunk/trunks/{trunkId}" : {
      "delete" : {
        "tags" : [ "accounts", "{account Id}", "sip trunk", "trunks" ],
        "summary" : "Delete a SIP trunk",
        "description" : "Use this API to remove existing SIP trunk of a sub account.<br>\n<br><b>Prerequisites:</b><br>\n* The account making this API request must be a master account with [API Partner Plan](https://zoom.us/plan/api) and SIP Connected Audio Plan.<br><br>\n**Scope:** `sip_trunk:master`",
        "operationId" : "deleteASipTrunk"
      }
    },
    "/accounts/{accountId}/trusted_domains" : {
      "get" : {
        "tags" : [ "accounts", "{account Id}" ],
        "summary" : "Get trusted domains",
        "description" : "Get trusted domains of a sub account. To get the trusted domains of a master account, use `me` as the value for the `accountId` path parameter.\n\n**Prerequisites:**<br>\n* The sub account must be a paid account.<br>\n**Scope:** `account:read:admin`<br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId" : "getTrustedDomains"
      }
    },
    "/accounts/{accountId}/users/{userId}/account" : {
      "put" : {
        "tags" : [ "accounts", "{account Id}" ],
        "summary" : "Switch a user's account",
        "description" : "Disassociate a user from one Account and move the user to another Account under the same master account. \n\nWith this API, a user under a master account or a sub account can be moved to another sub account within the same master account. To move a user from a master account to a sub account, use `me` as the value for `accountId`. In this scenario, \"me\" refers to the Account ID of the master account. \n\nTo move a user from one sub account to another sub account, provi[...]",
        "operationId" : "switchAUserSAccount"
      }
    },
    "/archive_files" : {
      "get" : {
        "summary" : "List archived files",
        "description" : "Zoom’s [archiving solution](https://support.zoom.us/hc/en-us/articles/360050431572-Archiving-Meeting-and-Webinar-data) allows account administrators to set up an automated mechanism to record, collect and archive meeting data to a 3rd party platform of their choice and hence, satisfy FINRA and/ or other compliance requirements.<br><br>\nUse this API to retrieve archived meeting or webinar files of an account.\n\n**Scope:** `recording:read:admin`<br>\n**[Rate Limit Label][...]",
        "operationId" : "listArchivedFiles"
      }
    },
    "/contacts" : {
      "get" : {
        "summary" : "Search company contacts",
        "description" : "A user under an organization's Zoom account has internal users listed under Company Contacts in the Zoom Client. Use this API to search users that are in the company contacts of a Zoom account. Using the `search_key` query parameter, provide either first name, last name or the email address of the user that you would like to search for. Optionally, set `query_presence_status` to `true` in order to include the presence status of a contact. <br><br>\n\n**Scopes:** `contact[...]",
        "operationId" : "searchCompanyContacts"
      }
    },
    "/meetings/{meetingId}" : {
      "get" : {
        "tags" : [ "meetings/{meeting Id}" ],
        "summary" : "Get a meeting",
        "description" : "Retrieve the details of a meeting.<br><br>\n**Scopes:** `meeting:read:admin` `meeting:read`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n",
        "operationId" : "getAMeeting"
      },
      "delete" : {
        "tags" : [ "meetings/{meeting Id}" ],
        "summary" : "Delete a meeting",
        "description" : "Delete a meeting.<br><br>\n**Scopes:** `meeting:write:admin` `meeting:write`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n\n",
        "operationId" : "deleteAMeeting"
      },
      "patch" : {
        "tags" : [ "meetings/{meeting Id}" ],
        "summary" : "Update a meeting",
        "description" : "Update the details of a meeting.<br>This API has a rate limit of 100 requests per day. Therefore, a meeting can only be updated for a maximum of 100 times within a 24 hour window.<br>\n**Scopes:** `meeting:write:admin` `meeting:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n",
        "operationId" : "updateAMeeting"
      }
    },
    "/meetings/{meetingId}/batch_polls" : {
      "post" : {
        "tags" : [ "meetings/{meeting Id}" ],
        "summary" : "Perform batch poll creation",
        "description" : "Polls allow the meeting host to survey attendees. Use this API to create batch [polls](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings) for a meeting.<br><br>\n\n**Scopes**: `meeting:write:admin` `meeting:write`<br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n**Prerequisites**:<br>\n* Host user type must be **Pro** or higher plan.\n* Polling feature must be enabled in the host's a[...]",
        "operationId" : "performBatchPollCreation"
      }
    },
    "/meetings/{meetingId}/invitation" : {
      "get" : {
        "tags" : [ "meetings/{meeting Id}" ],
        "summary" : "Get meeting invitation",
        "description" : "Retrieve the meeting invite note that was sent for a specific meeting.<br><br>\n**Scopes:** `meeting:read:admin` `meeting:read`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n",
        "operationId" : "getMeetingInvitation"
      }
    },
    "/meetings/{meetingId}/registrants" : {
      "get" : {
        "tags" : [ "meetings/{meeting Id}", "registrants" ],
        "summary" : "List meeting registrants",
        "description" : "A host or a user with admin permission can require [registration for a Zoom meeting](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings). Use this API to list users that have registered for a meeting.<br><br>\n**Scopes**: `meeting:read:admin` `meeting:read`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
        "operationId" : "listMeetingRegistrants"
      },
      "post" : {
        "tags" : [ "meetings/{meeting Id}", "registrants" ],
        "summary" : "Add meeting registrant",
        "description" : "Register a participant for a meeting.<br><br> Note that there is a maximum limit of 4999 registrants per meeting and users will see an error if the capacity has reached.\n\n**Prerequisite:**<br>\n* Host user type must be \"Licensed\".\n\n**Scopes:** `meeting:write:admin` `meeting:write`\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId" : "addMeetingRegistrant"
      }
    },
    "/meetings/{meetingId}/registrants/questions" : {
      "get" : {
        "tags" : [ "meetings/{meeting Id}", "registrants", "questions" ],
        "summary" : "List registration questions ",
        "description" : "List registration questions that will be displayed to users while [registering for a meeting](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings).<br>\n\n**Scopes:** `meeting:read`, `meeting:read:admin`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n",
        "operationId" : "listRegistrationQuestions"
      },
      "patch" : {
        "tags" : [ "meetings/{meeting Id}", "registrants", "questions" ],
        "summary" : "Update registration questions",
        "description" : "Update registration questions that will be displayed to users while [registering for a meeting](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings).<br><br>\n**Scopes:** `meeting:write`, `meeting:write:admin`<br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n \n\n",
        "operationId" : "updateRegistrationQuestions"
      }
    },
    "/meetings/{meetingId}/registrants/status" : {
      "put" : {
        "tags" : [ "meetings/{meeting Id}", "registrants" ],
        "summary" : "Update registrant's status",
        "description" : "Update a meeting registrant's status by either approving, cancelling or denying a registrant from joining the meeting.<br><br>\n**Scopes:** `meeting:write:admin` `meeting:write`\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
        "operationId" : "updateRegistrantSStatus"
      }
    },
    "/meetings/{meetingId}/registrants/{registrantId}" : {
      "delete" : {
        "tags" : [ "meetings/{meeting Id}", "registrants" ],
        "summary" : "Delete a meeting registrant",
        "description" : "Delete a meeting registrant.<br><br>\n**Scopes**: `meeting:write:admin` `meeting:write`<br>\n <br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId" : "deleteAMeetingRegistrant"
      }
    },
    "/meetings/{meetingId}/status" : {
      "put" : {
        "tags" : [ "meetings/{meeting Id}" ],
        "summary" : "Update meeting status",
        "description" : "Update the status of a meeting.<br><br>\n**Scopes:** `meeting:write:admin` `meeting:write`\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId" : "updateMeetingStatus"
      }
    },
    "/metrics/client/feedback" : {
      "get" : {
        "tags" : [ "metrics", "client", "feedback" ],
        "summary" : "List Zoom meetings client feedback",
        "description" : "Retrieve survey results from [Zoom meetings client feedback](https://support.zoom.us/hc/en-us/articles/115005855266-End-of-Meeting-Feedback-Survey#h_e30d552b-6d8e-4e0a-a588-9ca8180c4dbf). <br> You can specify a monthly date range for the dashboard data using the `from` and `to` query parameters. The month should fall within the last six months.\n\n**Prerequisites:**\n* Business or higher account\n* [Feedback to Zoom](https://support.zoom.us/hc/en-us/articles/115005838023[...]",
        "operationId" : "listZoomMeetingsClientFeedback"
      }
    },
    "/metrics/client/feedback/{feedbackId}" : {
      "get" : {
        "tags" : [ "metrics", "client", "feedback" ],
        "summary" : "Get zoom meetings client feedback",
        "description" : "Retrieve detailed information on a [Zoom meetings client feedback](https://support.zoom.us/hc/en-us/articles/115005855266-End-of-Meeting-Feedback-Survey#h_e30d552b-6d8e-4e0a-a588-9ca8180c4dbf). <br> You can specify a monthly date range for the dashboard data using the `from` and `to` query parameters. The month should fall within the last six months.\n\n**Prerequisites:**\n* Business or higher account\n* [Feedback to Zoom](https://support.zoom.us/hc/en-us/articles/115005[...]",
        "operationId" : "getZoomMeetingsClientFeedback"
      }
    },
    "/metrics/client/satisfaction" : {
      "get" : {
        "tags" : [ "metrics", "client" ],
        "summary" : "List client meeting satisfaction",
        "description" : "If the [End of Meeting Feedback Survey](https://support.zoom.us/hc/en-us/articles/115005855266) option is enabled, attendees will be prompted with a survey window where they can tap either the **Thumbs Up** or **Thumbs Down** button that indicates their Zoom meeting experience. With this API, you can get information on the attendees' meeting satisfaction. Specify a monthly date range for the query using the from and to query parameters. The month should fall within the l[...]",
        "operationId" : "listClientMeetingSatisfaction"
      }
    },
    "/metrics/meetings" : {
      "get" : {
        "tags" : [ "metrics", "meetings1" ],
        "summary" : "List meetings",
        "description" : "List total live or past meetings that occurred during a specified period of time. This overview will show if features such as audio, video, screen sharing, and recording were being used in the meeting. You can also see the license types of each user on your account.<br> You can specify a monthly date range for the dashboard data using the `from` and `to` query parameters. The month should fall within the last six months.<br>\n**Scopes:** `dashboard_meetings:read:admin`<b[...]",
        "operationId" : "listMeetings1"
      }
    },
    "/metrics/meetings/{meetingId}" : {
      "get" : {
        "tags" : [ "metrics", "meetings1", "{meeting Id}1" ],
        "summary" : "Get meeting details",
        "description" : "Get details on live or past meetings. This overview will show if features such as audio, video, screen sharing, and recording were being used in the meeting. You can also see the license types of each user on your account.<br> You can specify a monthly date range for the dashboard data using the `from` and `to` query parameters. The month should fall within the last six months.  <br>\n**Scopes:** `dashboard_meetings:read:admin`<br>\n **[Rate Limit Label](https://marketpl[...]",
        "operationId" : "getMeetingDetails"
      }
    },
    "/metrics/meetings/{meetingId}/participants" : {
      "get" : {
        "tags" : [ "metrics", "meetings1", "{meeting Id}1", "participants" ],
        "summary" : "List meeting participants",
        "description" : "Get a list of participants from live or past meetings.<br><br>\nIf you do not provide the `type` query parameter, the default value will be set to `live` and thus, you will only see metrics for participants in a live meeting, if any meeting is currently being conducted. To view metrics on past meeting participants, provide the appropriate value for `type`. <br> You can specify a monthly date range for the dashboard data using the `from` and `to` query parameters. The mon[...]",
        "operationId" : "listMeetingParticipants"
      }
    },
    "/metrics/meetings/{meetingId}/participants/qos" : {
      "get" : {
        "tags" : [ "metrics", "meetings1", "{meeting Id}1", "participants" ],
        "summary" : "List meeting participants QoS",
        "description" : "Get a list of meeting participants from live or past meetings along with the quality of service they recieve during the meeting such as connection quality for sending/receiving video, audio, and shared content.<br>If you do not provide the `type` query parameter, the default value will be set to `live` and thus, you will only see metrics for participants in a live meeting, if any meeting is currently being conducted. To view metrics on past meeting participants, provide [...]",
        "operationId" : "listMeetingParticipantsQoS"
      }
    },
    "/metrics/meetings/{meetingId}/participants/satisfaction" : {
      "get" : {
        "tags" : [ "metrics", "meetings1", "{meeting Id}1", "participants" ],
        "summary" : "Get post meeting feedback",
        "description" : "When a meeting ends, each attendee will be prompted to share their meeting experience by clicking either thumbs up or thumbs down. Use this API to retrieve the feedback submitted for a specific meeting. Note that this API only works for meetings scheduled after December 20, 2020.\n\n**Prerequisites:**\n* [Feedback to Zoom](https://support.zoom.us/hc/en-us/articles/115005838023) setting must be enabled by the participant prior to the meeting.\n* The user making the API re[...]",
        "operationId" : "getPostMeetingFeedback"
      }
    },
    "/metrics/meetings/{meetingId}/participants/sharing" : {
      "get" : {
        "tags" : [ "metrics", "meetings1", "{meeting Id}1", "participants" ],
        "summary" : "Get sharing/recording details",
        "description" : "Retrieve the sharing and recording details of participants from live or past meetings.<br>\n**Scopes:** `dashboard_meetings:read:admin`<br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>\n**Prerequisites:** <br>\n* Business or a higher plan.",
        "operationId" : "getSharingRecordingDetails"
      }
    },
    "/metrics/meetings/{meetingId}/participants/{participantId}/qos" : {
      "get" : {
        "tags" : [ "metrics", "meetings1", "{meeting Id}1", "participants" ],
        "summary" : "Get meeting participant QoS",
        "description" : "Retrieve the quality of service for participants from live or past meetings. This data indicates the connection quality for sending/receiving video, audio, and shared content. If nothing is being sent or received at that time, no information will be shown in the fields. <br><br>\n**Scopes:** `dashboard_meetings:read:admin`<br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
        "operationId" : "getMeetingParticipantQoS"
      }
    },
    "/metrics/webinars" : {
      "get" : {
        "tags" : [ "metrics", "webinars1" ],
        "summary" : "List webinars",
        "description" : "List all the live or past webinars from a specified period of time. <br><br>\n**Scopes:** `dashboard_webinars:read:admin`<br>\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Resource-intensive`<br>\n**Prerequisites:**<br>\n* Business, Education or API Plan with Webinar add-on.\n\n\n",
        "operationId" : "listWebinars1"
      }
    },
    "/metrics/webinars/{webinarId}" : {
      "get" : {
        "tags" : [ "metrics", "webinars1", "{webinar Id}" ],
        "summary" : "Get webinar details",
        "description" : "Retrieve details from live or past webinars.<br><br>\n**Scopes:** `dashboard_webinars:read:admin`<br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>\n**Prerequisites:**<br>\n* Business, Education or API Plan with Webinar add-on.\n\n",
        "operationId" : "getWebinarDetails"
      }
    },
    "/metrics/webinars/{webinarId}/participants" : {
      "get" : {
        "tags" : [ "metrics", "webinars1", "{webinar Id}", "participants1" ],
        "summary" : "Get webinar participants",
        "description" : "Retrieve details on participants from live or past webinars.<br><br>\n**Scopes:** `dashboard_webinars:read:admin`<br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>\n**Prerequisites:**<br>\n* Business, Education or API Plan with Webinar add-on.\n\n",
        "operationId" : "getWebinarParticipants"
      }
    },
    "/metrics/webinars/{webinarId}/participants/qos" : {
      "get" : {
        "tags" : [ "metrics", "webinars1", "{webinar Id}", "participants1" ],
        "summary" : "List webinar participant QoS",
        "description" : "Retrieve a list of participants from live or past webinars and the quality of service they received.<br>This data indicates the connection quality for sending/receiving video, audio, and shared content. If nothing is being sent or received at that time, no information will be shown in the fields.<br>\n**Scopes:** `dashboard_webinars:read:admin`<br> \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>\n**Prerequisi[...]",
        "operationId" : "listWebinarParticipantQoS"
      }
    },
    "/metrics/webinars/{webinarId}/participants/satisfaction" : {
      "get" : {
        "tags" : [ "metrics", "webinars1", "{webinar Id}", "participants1" ],
        "summary" : "Get post webinar feedback",
        "description" : "When a Webinar ends, each attendee will be prompted to share their Webinar experience by clicking either thumbs up or thumbs down. Use this API to retrieve the feedback submitted for a specific webinar. Note that this API only works for meetings scheduled after December 20, 2020.\n\n**Prerequisites:**\n* [Feedback to Zoom](https://support.zoom.us/hc/en-us/articles/115005838023) setting must be enabled by the participant prior to the meeting.\n* The user making the API re[...]",
        "operationId" : "getPostWebinarFeedback"
      }
    },
    "/metrics/webinars/{webinarId}/participants/sharing" : {
      "get" : {
        "tags" : [ "metrics", "webinars1", "{webinar Id}", "participants1" ],
        "summary" : "Get sharing/recording details",
        "description" : "Retrieve the sharing and recording details of participants from live or past webinars. <br><br>\n**Scopes:** `dashboard_webinars:read:admin`<br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy` <br>\n**Prerequisites:**<br>\n* Business, Education or API Plan with Webinar add-on.\n\n",
        "operationId" : "getSharingRecordingDetails1"
      }
    },
    "/metrics/webinars/{webinarId}/participants/{participantId}/qos" : {
      "get" : {
        "tags" : [ "metrics", "webinars1", "{webinar Id}", "participants1" ],
        "summary" : "Get webinar participant QoS",
        "description" : "Retrieve details on the quality of service that participants from live or past webinars recieved.<br>This data indicates the connection quality for sending/receiving video, audio, and shared content. If nothing is being sent or received at that time, no information will be shown in the fields.<br>\n**Scopes:** `dashboard_webinars:read:admin`<br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy` <br>\n**Prerequisites[...]",
        "operationId" : "getWebinarParticipantQoS"
      }
    },
    "/past_meetings/{meetingId}/files" : {
      "get" : {
        "tags" : [ "past meetings", "{meeting Id}" ],
        "summary" : "List past meeting's files",
        "description" : "**Note: This API has been deprecated and is no longer supported due to GCM encryption updates for security purposes.** To learn about saving the in-meeting chat files via Zoom Client, refer to the [Saving in-meeting chat](https://support.zoom.us/hc/en-us/articles/115004792763-Saving-in-meeting-chat) guide.\n\nList files sent via in-meeting chat during a meeting. The in-meeting files are deleted after 24 hours of the meeting completion time. \n<br><br>\n**Scope:** `meetin[...]",
        "operationId" : "listPastMeetingSFiles"
      }
    },
    "/past_meetings/{meetingId}/instances" : {
      "get" : {
        "tags" : [ "past meetings", "{meeting Id}" ],
        "summary" : "List ended meeting instances",
        "description" : "Get a list of ended meeting instances<br><br>\n**Scopes:** `meeting:read:admin` `meeting:read`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` ",
        "operationId" : "listEndedMeetingInstances"
      }
    },
    "/past_meetings/{meetingId}/polls" : {
      "get" : {
        "tags" : [ "past meetings", "{meeting Id}" ],
        "summary" : "List past meeting's poll results",
        "description" : "[Polls](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings) allow the meeting host to survey attendees. Use this API to list poll results of a meeting.<br><br>\n\n**Scopes**: `meeting:read:admin`, `meeting:read`<br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` <br>\n**Prerequisites**:<br>\n* Host user type must be **Pro**.\n* Meeting must be a scheduled meeting. Instant meetings do not ha[...]",
        "operationId" : "listPastMeetingSPollResults"
      }
    },
    "/past_meetings/{meetingUUID}" : {
      "get" : {
        "tags" : [ "past meetings", "{meeting UUID}" ],
        "summary" : "Get past meeting details",
        "description" : "Get details on a past meeting. <br><br>\n**Scopes:** `meeting:read:admin` `meeting:read`\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n> **Note**: Please double encode your UUID when using this API if the UUID begins with a '/'or contains '//' in it.",
        "operationId" : "getPastMeetingDetails"
      }
    },
    "/past_meetings/{meetingUUID}/participants" : {
      "get" : {
        "tags" : [ "past meetings", "{meeting UUID}" ],
        "summary" : "Get past meeting participants",
        "description" : "Retrieve information on participants from a past meeting. <br><br>\n**Scopes:** `meeting:read:admin` `meeting:read`\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`\n**Prerequisites:**<br>\n* Paid account on a Pro or higher plan.\n\n<br> <br>  **Note**: Please double encode your UUID when using this API if the UUID begins with a '/'or contains '//' in it.\n",
        "operationId" : "getPastMeetingParticipants"
      }
    },
    "/past_webinars/{WebinarUUID}/absentees" : {
      "get" : {
        "tags" : [ "past webinars" ],
        "summary" : "Get webinar absentees",
        "description" : "List absentees of a webinar.<br><br>\n**Scopes:** `webinar:read:admin` `webinar:read`<br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
        "operationId" : "getWebinarAbsentees"
      }
    },
    "/past_webinars/{webinarId}/files" : {
      "get" : {
        "tags" : [ "past webinars", "{webinar Id}1" ],
        "summary" : "List past webinar files",
        "description" : "**Note: This API has been deprecated and is no longer supported due to GCM encryption updates for security purposes.**\n\nList files sent via in-meeting chat during a meeting. The in-meeting files are deleted after 24 hours of the meeting completion time. \n<br><br>\n**Scope:** `webinar:read`, `webinar:read:admin`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>\n\n",
        "operationId" : "listPastWebinarFiles"
      }
    },
    "/past_webinars/{webinarId}/instances" : {
      "get" : {
        "tags" : [ "past webinars", "{webinar Id}1" ],
        "summary" : "List past webinar instances",
        "description" : "List past webinar instances.<br><br>\n**Scopes:** `webinar:read:admin` `webinar:read`<br>\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n\n",
        "operationId" : "listPastWebinarInstances"
      }
    },
    "/past_webinars/{webinarId}/participants" : {
      "get" : {
        "tags" : [ "past webinars", "{webinar Id}1" ],
        "summary" : "List webinar participants",
        "description" : "Use this API to list all the participants who attended a webinar hosted in the past. <br>\n\n**Prerequisites:**\n* Pro or higher plan with a Webinar Add-on.<br>\n**Scopes:** `webinar:read:admin` `webinar:read`<br> \n<br>\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>\n\n\n\n",
        "operationId" : "listWebinarParticipants"
      }
    },
    "/past_webinars/{webinarId}/polls" : {
      "get" : {
        "tags" : [ "past webinars", "{webinar Id}1" ],
        "summary" : "List past webinar poll results",
        "description" : "The polling feature for webinar allows you to create single choice or multiple choice polling questions for your webinars. Use this API to retrieve the results for Webinar Polls of a specific Webinar.\n\n**Prerequisites:**<br>\n* [Webinar license](https://zoom.us/webinar)<br>\n**Scopes**: `webinar:read:admin`, `webinar:read`<br>\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`\n\n",
        "operationId" : "listPastWebinarPollResults"
      }
    },
    "/past_webinars/{webinarId}/qa" : {
      "get" : {
        "tags" : [ "past webinars", "{webinar Id}1" ],
        "summary" : "List Q&A of past webinar",
        "description" : "The [Question & Answer (Q&A)](https://support.zoom.us/hc/en-us/articles/203686015-Getting-Started-with-Question-Answer) feature for Webinars allows attendees to ask questions during the Webinar and for the panelists, co-hosts and host to answer their questions.<br>\nUse this API to list Q&A of a specific Webinar.\n\n**Prerequisites:**<br>\n* [Webinar license](https://zoom.us/webinar)<br>\n**Scopes**: `webinar:read:admin`, `webinar:read`<br>\n <br>\n\n\n **[Rate Limit Lab[...]",
        "operationId" : "listQAOfPastWebinar"
      }
    },
    "/report/activities" : {
      "get" : {
        "tags" : [ "report" ],
        "summary" : "Get sign In / sign out activity report",
        "description" : "Retrieve a list of sign in / sign out activity logs [report](https://support.zoom.us/hc/en-us/articles/201363213-Getting-Started-with-Reports) of users under a Zoom account.<br>\n**Prerequisites**<br>\n* Pro or higher plan.<br>\n**Scopes:** `report:read:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
        "operationId" : "getSignInSignOutActivityReport"
      }
    },
    "/report/cloud_recording" : {
      "get" : {
        "tags" : [ "report" ],
        "summary" : "Get cloud recording usage report",
        "description" : "Retrieve cloud recording usage report for a specified period. You can only get cloud recording reports that is one day ealier than the current date and for the most recent period of 6 months. The date gap between from and to dates should be smaller or equal to 30 days. <br>\n**Prerequisites**<br>\n* Pro or higher plan.<br>\n**Scopes:** `report:read:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
        "operationId" : "getCloudRecordingUsageReport"
      }
    },
    "/report/daily" : {
      "get" : {
        "tags" : [ "report" ],
        "summary" : "Get daily usage report",
        "description" : "Retrieve daily report to access the account-wide usage of Zoom services for each day in a given month. It lists the number of new users, meetings, participants, and meeting minutes.<br>\n**Prerequisites**<br>\n* Pro or higher plan.<br>\n**Scopes:** `report:read:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
        "operationId" : "getDailyUsageReport"
      }
    },
    "/report/meetings/{meetingId}" : {
      "get" : {
        "tags" : [ "report", "meetings/{meeting Id}1" ],
        "summary" : "Get meeting detail reports",
        "description" : "Get a detailed report for a past meeting. <br>\n**Scopes:** `report:read:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>\n**Prerequisites:**<br>\n* Pro or a higher plan.<br>\n ",
        "operationId" : "getMeetingDetailReports"
      }
    },
    "/report/meetings/{meetingId}/participants" : {
      "get" : {
        "tags" : [ "report", "meetings/{meeting Id}1" ],
        "summary" : "Get meeting participant reports",
        "description" : "Get participant report for a past meeting.<br><br>\n**Scopes:** `report:read:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>\n**Prerequisites:**<br>\n* Pro or a higher plan.<br>\n ",
        "operationId" : "getMeetingParticipantReports"
      }
    },
    "/report/meetings/{meetingId}/polls" : {
      "get" : {
        "tags" : [ "report", "meetings/{meeting Id}1" ],
        "summary" : "Get meeting poll reports",
        "description" : "Retrieve a report of [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings) results for a past meeting. <br><br>\n**Scopes:** `report:read:admin`<br>\n \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>\n**Prerequisites:**<br>\n* Pro or a higher plan.<br>\n ",
        "operationId" : "getMeetingPollReports"
      }
    },
    "/report/operationlogs" : {
      "get" : {
        "tags" : [ "report" ],
        "summary" : "Get operation logs report",
        "description" : "The [Operations Logs](https://support.zoom.us/hc/en-us/articles/360032748331-Operation-Logs) report allows you to audit admin and user activity, such as adding a new user, changing account settings, and deleting recordings.<br>\nUse this API to retrieve operation logs report for a specified period of time.<br>\n**Scopes:** `report:read:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>\n**Prerequisi[...]",
        "operationId" : "getOperationLogsReport"
      }
    },
    "/report/telephone" : {
      "get" : {
        "tags" : [ "report" ],
        "summary" : "Get telephone reports",
        "description" : "The [telephone report](https://support.zoom.us/hc/en-us/articles/206514816-Telephone-reports) allows you to view who dialed into meetings via phone (Audio Conferencing or SIP Connected Audio) and which number they dialed into and other details. Use this API to get telephone report for a specified period of time.\n\n**Scopes:** `report:read:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>**Prerequi[...]",
        "operationId" : "getTelephoneReports"
      }
    },
    "/report/users" : {
      "get" : {
        "tags" : [ "report", "users1" ],
        "summary" : "Get active/inactive host reports",
        "description" : "A user is considered to be an active host during the month specified in the \"from\" and \"to\" range, if the user has hosted at least one meeting during this period. If the user didn't host any meetings during this period, the user is considered to be inactive.<br>The Active Hosts report displays a list of meetings, participants, and meeting minutes for a specific time range, up to one month. The month should fall within the last six months.<br>The Inactive Hosts report[...]",
        "operationId" : "getActiveInactiveHostReports"
      }
    },
    "/report/users/{userId}/meetings" : {
      "get" : {
        "tags" : [ "report", "users1" ],
        "summary" : "Get meeting reports",
        "description" : "Retrieve [report](https://support.zoom.us/hc/en-us/articles/216378603-Meeting-Reporting) on a past meeting for a specified period of time. The time range for the report is limited to a month and the month should fall under the past six months.\n\nMeetings will only be returned in the response if the meeting has two or more unique participants.  <br><br>\n**Scopes:** `report:read:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limi[...]",
        "operationId" : "getMeetingReports"
      }
    },
    "/report/webinars/{webinarId}" : {
      "get" : {
        "tags" : [ "report", "webinars/{webinar Id}" ],
        "summary" : "Get webinar detail reports",
        "description" : "Retrieve a [report](https://support.zoom.us/hc/en-us/articles/201393719-Webinar-Reporting) containing past webinar details.  <br><br>\n**Scopes:** `report:read:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>\n**Prerequisites:**<br>\n* Pro or higher plan with Webinar add-on.",
        "operationId" : "getWebinarDetailReports"
      }
    },
    "/report/webinars/{webinarId}/participants" : {
      "get" : {
        "tags" : [ "report", "webinars/{webinar Id}" ],
        "summary" : "Get webinar participant reports",
        "description" : "Get detailed report on each attendee of a webinar.<br><br>\n**Scopes:** `report:read:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>\n**Prerequisites:**<br>\n* Pro or a higher plan with Webinar add-on enabled.",
        "operationId" : "getWebinarParticipantReports"
      }
    },
    "/report/webinars/{webinarId}/polls" : {
      "get" : {
        "tags" : [ "report", "webinars/{webinar Id}" ],
        "summary" : "Get webinar poll reports",
        "description" : "Retrieve a report on past [webinar polls](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars).<br><br>\n**Scopes:** `report:read:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>\n**Prerequisites:**<br>\n* Pro or a higher plan with Webinar add-on enabled.",
        "operationId" : "getWebinarPollReports"
      }
    },
    "/report/webinars/{webinarId}/qa" : {
      "get" : {
        "tags" : [ "report", "webinars/{webinar Id}" ],
        "summary" : "Get webinar Q&A report",
        "description" : "The Question & Answer (Q&A) feature for webinars allows attendees to ask questions during the webinar and for the panelists, co-hosts and host to answer their questions.\n\nUse this API to retrieve a report on question and answers from past webinars. <br><br>\n**Scopes:** `report:read:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`<br>\n**Prerequisites:**<br>\n* Pro or a higher plan with Webinar add-[...]",
        "operationId" : "getWebinarQAReport"
      }
    },
    "/tracking_fields" : {
      "get" : {
        "tags" : [ "tracking fields" ],
        "summary" : "List tracking fields",
        "description" : "[Tracking fields](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields) allow you to analyze usage by various fields within an organization.<br> Use this API to list all the tracking fields on your Zoom account.<br><br>\n**Scopes:** `trackingfield:read:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>\n**Prerequisites:**\n* Business, Education, API or higher plan",
        "operationId" : "listTrackingFields"
      },
      "post" : {
        "tags" : [ "tracking fields" ],
        "summary" : "Create a tracking field",
        "description" : "[Tracking fields](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields) allow you to analyze usage by various fields within an organization.<br> Use this API to create a new tracking field.<br><br>\n**Scope:** `trackingfield:write:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n**Prerequisites:**\n* Business, Education, API or higher plan",
        "operationId" : "createATrackingField"
      }
    },
    "/tracking_fields/{fieldId}" : {
      "get" : {
        "tags" : [ "tracking fields", "{field Id}" ],
        "summary" : "Get a tracking field",
        "description" : "[Tracking fields](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields) allow you to analyze usage by various fields within an organization.<br><br> When scheduling a meeting, the tracking field will be included in the meeting options.<br>Use this API to get information on a tracking field.<br><br>\n**Scopes:** `trackingfield:read:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `[...]",
        "operationId" : "getATrackingField"
      },
      "delete" : {
        "tags" : [ "tracking fields", "{field Id}" ],
        "summary" : "Delete a tracking field",
        "description" : "[Tracking fields](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields) allow you to analyze usage by various fields within an organization.<br> Use this API to delete a tracking field.<br><br>\n**Scope:** `trackingfield:write:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n**Prerequisites:**\n* Business, Education, API or higher plan",
        "operationId" : "deleteATrackingField"
      },
      "patch" : {
        "tags" : [ "tracking fields", "{field Id}" ],
        "summary" : "Update a tracking field",
        "description" : "[Tracking fields](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields) allow you to analyze usage by various fields within an organization.<br> Use this API to update a tracking field.<br><br>\n**Scope:** `trackingfield:write:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n**Prerequisites:**\n* Business, Education, API or higher plan",
        "operationId" : "updateATrackingField"
      }
    },
    "/users" : {
      "get" : {
        "tags" : [ "users" ],
        "summary" : "List users",
        "description" : "A Zoom account can have one or more users. Use this API to list users on your account.<br><br>\n**Scopes:** `user:read:admin`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
        "operationId" : "listUsers"
      },
      "post" : {
        "tags" : [ "users" ],
        "summary" : "Create users",
        "description" : "A Zoom account can have one or more users. Use this API to add a new user to your account.<br><br>\n**Prerequisites:**<br>\n* Pro or higher plan<br><br>\n**Scopes:** `user:write:admin` `user:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId" : "createUsers"
      }
    },
    "/users/email" : {
      "get" : {
        "tags" : [ "users" ],
        "summary" : "Check a user email",
        "description" : "Verify if a user's email is registered with Zoom.<br><br>\n\n<b>Note: </b>You can successfully check if a user is a registered Zoom user only if the user **signed up for Zoom via email and is within your account.** If you provide an email address of a user who is not in your account, the value of \"existed_email\" parameter will be \"false\" irrespective of whether or not the user is registered with Zoom. The response of this API call will not include users who joined Zo[...]",
        "operationId" : "checkAUserEmail"
      }
    },
    "/users/me/zak" : {
      "get" : {
        "tags" : [ "users" ],
        "summary" : "Get user's ZAK",
        "description" : "Get User’s Zoom Access Token (ZAK). You can use a ZAK to enable a non-login user to join a meeting on your app. Non-login users do not need to enter their username and password to join meetings.\n\n**Scope:** `user_zak:read`<br>\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n\n",
        "operationId" : "getUserSZak"
      }
    },
    "/users/vanity_name" : {
      "get" : {
        "tags" : [ "users" ],
        "summary" : "Check a user's PM room",
        "description" : "A personal meeting room is a virtual meeting room that can be permanently assigned to a user.\nUse this API to check if a personal meeting room with the given name exists or not.<br><br>\n**Scopes:** `user:read:admin` `user:read`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` ",
        "operationId" : "checkAUserSPmRoom"
      }
    },
    "/users/{userId}" : {
      "get" : {
        "tags" : [ "users", "{user Id}" ],
        "summary" : "Get a user",
        "description" : "A Zoom account can have one or more users. Use this API to view information of a specific user on a Zoom account.<br><br>\n**Scopes:** `user:read:admin` `user:read`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` \n<p style=\"background-color:#e1f5fe; color:#000000; padding:8px\"> <b>Note:</b> Users who have not activated their account have a status of <i>pending</i>, and the <i>created_at</i> time displays[...]",
        "operationId" : "getAUser"
      },
      "delete" : {
        "tags" : [ "users", "{user Id}" ],
        "summary" : "Delete a user",
        "description" : "Deleting a user permanently removes the user and their data from Zoom. Users can create a new Zoom account using the same email address. An account owner or an account admin can transfer meetings, webinars and cloud recordings to another Zoom user account before deleting.<br><br>\n\nThis API disassociates (unlinks) a user from the associated Zoom account and provides the user their own basic free Zoom account, and the user can purchase their own licenses. You can transfe[...]",
        "operationId" : "deleteAUser"
      },
      "patch" : {
        "tags" : [ "users", "{user Id}" ],
        "summary" : "Update a user",
        "description" : "Update information on a user's Zoom [profile](https://support.zoom.us/hc/en-us/articles/201363203-My-Profile).<br><br>\n**Scopes:** `user:write:admin` `user:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId" : "updateAUser"
      }
    },
    "/users/{userId}/assistants" : {
      "get" : {
        "tags" : [ "users", "{user Id}", "assistants" ],
        "summary" : "List user assistants",
        "description" : "List a user's assistants.\n\nAssistants are the users to whom the current user has assigned [scheduling privilege](https://support.zoom.us/hc/en-us/articles/201362803-Scheduling-Privilege). These assistants can schedule meeting on behalf of the current user as well as manage and act as an alternative host for all meetings if the admin has enabled [Co-host option](https://zoom.us/account/setting) on the account.<br><br>\n**Prerequisites**: <br>\n* Current user as well as [...]",
        "operationId" : "listUserAssistants"
      },
      "post" : {
        "tags" : [ "users", "{user Id}", "assistants" ],
        "summary" : "Add assistants",
        "description" : "Assistants are the users to whom the current user has assigned [scheduling privilege](https://support.zoom.us/hc/en-us/articles/201362803-Scheduling-Privilege). These assistants can schedule meeting on behalf of the current user as well as manage and act as an alternative host for all meetings if the admin has enabled [Co-host option](https://zoom.us/account/setting) on the account.<br>Use this API to assign assistants to a user. <br> In the request body, provide either [...]",
        "operationId" : "addAssistants"
      },
      "delete" : {
        "tags" : [ "users", "{user Id}", "assistants" ],
        "summary" : "Delete user assistants",
        "description" : "Delete all assistants of the current user.<br> Assistants are the users to whom the current user has assigned [scheduling privilege](https://support.zoom.us/hc/en-us/articles/201362803-Scheduling-Privilege). These assistants can schedule meeting on behalf of the current user as well as manage and act as an alternative host for all meetings if the admin has enabled [Co-host option](https://zoom.us/account/setting) on the account.<br>\n**Prerequisite**: \n* The user as wel[...]",
        "operationId" : "deleteUserAssistants"
      }
    },
    "/users/{userId}/assistants/{assistantId}" : {
      "delete" : {
        "tags" : [ "users", "{user Id}", "assistants" ],
        "summary" : "Delete a user assistant",
        "description" : "Delete a specific assistant of a user.\nAssistants are the users to whom the current user has assigned [scheduling privilege](https://support.zoom.us/hc/en-us/articles/201362803-Scheduling-Privilege). These assistants can schedule meeting on behalf of the current user as well as manage and act as an alternative host for all meetings if the admin has enabled [Co-host option](https://zoom.us/account/setting) on the account.<br><br>\n**Prerequisites**: \n* The user as well [...]",
        "operationId" : "deleteAUserAssistant"
      }
    },
    "/users/{userId}/email" : {
      "put" : {
        "tags" : [ "users", "{user Id}" ],
        "summary" : "Update a user's email",
        "description" : "Change a user's [email address](https://support.zoom.us/hc/en-us/articles/201362563-How-Do-I-Change-the-Email-on-My-Account-) on a Zoom account that has managed domain set up.<br>If the Zoom Account in which the user belongs, has multiple [managed domains](https://support.zoom.us/hc/en-us/articles/203395207-What-is-Managed-Domain-), the email to be updated must match one of the managed domains.<br>\n**Scopes:** `user:write:admin` `user:write`<br>\n **[Rate Limit Label](h[...]",
        "operationId" : "updateAUserSEmail"
      }
    },
    "/users/{userId}/meeting_templates" : {
      "get" : {
        "tags" : [ "users", "{user Id}" ],
        "summary" : "List meeting templates",
        "description" : "Use this API to list [meeting templates](https://support.zoom.us/hc/en-us/articles/360036559151-Meeting-templates) that are available to be used by a user.\n\n**Scope:** `meeting:read` or `meeting:read:admin`\n\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`\n",
        "operationId" : "listMeetingTemplates"
      }
    },
    "/users/{userId}/meetings" : {
      "get" : {
        "tags" : [ "users", "{user Id}", "meetings" ],
        "summary" : "List meetings",
        "description" : "List all the meetings that were scheduled for a user (meeting host). This API only supports scheduled meetings and thus, details on instant meetings are not returned via this API.<br><br>\n**Scopes:** `meeting:read:admin` `meeting:read`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
        "operationId" : "listMeetings"
      },
      "post" : {
        "tags" : [ "users", "{user Id}", "meetings" ],
        "summary" : "Create a meeting",
        "description" : "[Create a meeting](https://support.zoom.us/hc/en-us/articles/201362413-Scheduling-meetings) for a user. <br>This API has a daily rate limit of 100 requests per day. Therefore, only 100 **Create a Meeting** API requests are permitted within a 24 hour window for a user.<br>\n\n<aside>The <code>start_url</code> of a meeting is a URL using which a host or an alternative host can start a meeting. The expiration time for the <code>start_url</code> field is two hours for all re[...]",
        "operationId" : "createAMeeting"
      }
    },
    "/users/{userId}/pac" : {
      "get" : {
        "tags" : [ "users", "{user Id}" ],
        "summary" : "List a user's PAC accounts",
        "description" : "[Personal Audio Conference](https://support.zoom.us/hc/en-us/articles/204517069-Getting-Started-with-Personal-Audio-Conference) (PAC) allows Pro or higher account holders to host meetings through PSTN (phone dial-in) only.<br>Use this API to list a user's PAC accounts.<br><br>\n**Scopes:** `pac:read:admin` `pac:read`<br>\n<br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n**Prerequisites:**<br>\n* A Pro or [...]",
        "operationId" : "listAUserSPacAccounts"
      }
    },
    "/users/{userId}/password" : {
      "put" : {
        "tags" : [ "users", "{user Id}" ],
        "summary" : "Update a user's password",
        "description" : "Update the [password](https://support.zoom.us/hc/en-us/articles/206344385-Change-a-User-s-Password) of a user using which the user can login to Zoom.<br> After this request is processed successfully, an email notification will be sent to the user stating that the password was changed.<br>\n**Scopes:** `user:write:admin` `user:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`\n**Prerequisites:**<br>\n*[...]",
        "operationId" : "updateAUserSPassword"
      }
    },
    "/users/{userId}/permissions" : {
      "get" : {
        "tags" : [ "users", "{user Id}" ],
        "summary" : "Get user permissions",
        "description" : "Users can be assigned a set of permissions that allows them to access only the pages/information that a user needs to view or edit.<br>\n\nUse this API to get permissions that have been granted to the user.<br><br>\n**Scopes:** `user:read:admin` `user:read`<br>\n \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId" : "getUserPermissions"
      }
    },
    "/users/{userId}/picture" : {
      "post" : {
        "tags" : [ "users", "{user Id}" ],
        "summary" : "Upload a user's profile picture",
        "description" : "Upload a user's profile picture.<br><br>\n\nProvide `multipart/form-data` as the value of the `content-type` header for this request. This API supports JPEG and PNG file formats.\n\n**Scopes:** `user:write:admin` `user:write`<br>\n \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
        "operationId" : "uploadAUserSProfilePicture"
      }
    },
    "/users/{userId}/presence_status" : {
      "put" : {
        "tags" : [ "users", "{user Id}" ],
        "summary" : "Update a user's presence status",
        "description" : "Users in the Zoom desktop client and mobile apps are assigned with a [presence status](https://support.zoom.us/hc/en-us/articles/360032554051-Status-Icons). The presence status informs users of their contact's availability. Users can also change their own presence status to be either \"Away\", \"Do not disturb\", or \"Available\".\n\nUse this API to update a user's presence status. A user's status can not be updated more than once per minute, i.e., you can only submit a [...]",
        "operationId" : "updateAUserSPresenceStatus"
      }
    },
    "/users/{userId}/recordings" : {
      "get" : {
        "tags" : [ "users", "{user Id}" ],
        "summary" : "List all recordings",
        "description" : "When a user records a meeting or a webinar by choosing the **Record to the Cloud** option, the video, audio, and chat text are recorded in the Zoom cloud. \n\nUse this API to list all [Cloud recordings](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording) of a user.<br>\n> To access a user's password protected cloud recording, add an \"access_token\" parameter to the download URL and provide either the [JWT](https://marketplace.zoom.us/docs/guides/getting[...]",
        "operationId" : "listAllRecordings"
      }
    },
    "/users/{userId}/schedulers" : {
      "get" : {
        "tags" : [ "users", "{user Id}", "schedulers" ],
        "summary" : "List user schedulers",
        "description" : "List all the schedulers of a user. Schedulers in this context are the users for whom the current user can schedule meetings for.\n\nFor instance, if the current user (i.e., the user whose userId was passed in the path parameter of this API call) is user A, the response of this API will contain a list of user(s), for whom user A can schedule and manage meetings. User A is the assistant of these users and thus has scheduling privilege for these user(s). \n\n**Prerequisites[...]",
        "operationId" : "listUserSchedulers"
      },
      "delete" : {
        "tags" : [ "users", "{user Id}", "schedulers" ],
        "summary" : "Delete user schedulers",
        "description" : "Delete all of a user's schedulers. Schedulers are users on whose behalf the current user (assistant) can schedule meetings for. By calling this API, the current user will no longer be a scheduling assistant of any user. \n\n**Prerequisite**: Current user (assistant) must be under the same account as the scheduler.<br>\n**Scopes**: `user:write:admin` `user:write`\n \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId" : "deleteUserSchedulers"
      }
    },
    "/users/{userId}/schedulers/{schedulerId}" : {
      "delete" : {
        "tags" : [ "users", "{user Id}", "schedulers" ],
        "summary" : "Delete a scheduler",
        "description" : "Delete a Scheduler.\n\nSchedulers are users on whose behalf the current user (assistant) can schedule meetings for. By calling this API, the current user will no longer be a scheduling assistant of this scheduler. \n\n**Prerequisite**: Current user must be under the same account as the scheduler.<br>\n**Scopes**: `user:write:admin` `user:write`\n \n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId" : "deleteAScheduler"
      }
    },
    "/users/{userId}/settings" : {
      "get" : {
        "tags" : [ "users", "{user Id}", "settings1" ],
        "summary" : "Get user settings",
        "description" : "Retrieve a user's settings.<br><br>\n**Scopes:** `user:read:admin` `user:read`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
        "operationId" : "getUserSettings"
      },
      "patch" : {
        "tags" : [ "users", "{user Id}", "settings1" ],
        "summary" : "Update user settings",
        "description" : "Update a user's settings.<br><br>\n**Scopes:** `user:write:admin` `user:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
        "operationId" : "updateUserSettings"
      }
    },
    "/users/{userId}/settings/virtual_backgrounds" : {
      "post" : {
        "tags" : [ "users", "{user Id}", "settings1", "virtual backgrounds1" ],
        "summary" : "Upload virtual background files",
        "description" : "Use this API to [upload virtual background files](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background) for a user. \n\n**Prerequisites:**<br>\n* Virtual background feature must be [enabled](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background#h_2ef28080-fce9-4ac2-b567-dc958afab1b7) on the account.\n<br> **Scope:** `user:write:admin`\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Mediu[...]",
        "operationId" : "uploadVirtualBackgroundFiles1"
      },
      "delete" : {
        "tags" : [ "users", "{user Id}", "settings1", "virtual backgrounds1" ],
        "summary" : "Delete virtual background files",
        "description" : "Delete existing virtual background file(s) of a user. \n\n**Prerequisites:**<br>\n* Virtual background feature must be [enabled](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background#h_2ef28080-fce9-4ac2-b567-dc958afab1b7) on the account.\n<br> **Scope:** `user:write:admin`<br>\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n\n",
        "operationId" : "deleteVirtualBackgroundFiles1"
      }
    },
    "/users/{userId}/status" : {
      "put" : {
        "tags" : [ "users", "{user Id}" ],
        "summary" : "Update user status",
        "description" : "An account owner or admins can deactivate as well as activate a user in a Zoom account. Deactivating a user will remove all licenses associated with a user. It will prevent the deactivated user from logging into their Zoom account. A deactivated user can be reactivated. Reactivating a user grants the user access to login to their Zoom account.<br> Use this API to either [deactivate](https://support.zoom.us/hc/en-us/articles/115005269946-Remove-User-from-your-Account#h_6a[...]",
        "operationId" : "updateUserStatus"
      }
    },
    "/users/{userId}/token" : {
      "get" : {
        "tags" : [ "users", "{user Id}", "token" ],
        "summary" : "Get a user token",
        "description" : "Retrieve a user's token.<br><br> This token is used for starting meetings with the Client SDK.<br>\n**Scopes:** `user:read:admin` `user:read`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\nIf a user signed into Zoom using Google or Facebook, a null value will be returned for the token. To get the token with this API, ask the user to sign into Zoom using their email and password instead.",
        "operationId" : "getAUserToken"
      },
      "delete" : {
        "tags" : [ "users", "{user Id}", "token" ],
        "summary" : "Revoke a user's SSO token",
        "description" : "Revoke a user's SSO token.<br><br> After calling this API, the SSO user will be logged out of their current Zoom session.<br>\n**Scopes:** `user:write:admin` `user:write`\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId" : "revokeAUserSSsoToken"
      }
    },
    "/users/{userId}/tsp" : {
      "get" : {
        "tags" : [ "users", "{user Id}", "tsp" ],
        "summary" : "List user's TSP accounts",
        "description" : "A user can have a maximum of two TSP accounts. Use this API to list all TSP accounts of a user.<br><br>\n**Scopes:** `tsp:read:admin` `tsp:read`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
        "operationId" : "listUserSTspAccounts"
      },
      "post" : {
        "tags" : [ "users", "{user Id}", "tsp" ],
        "summary" : "Add a user's TSP account",
        "description" : "Add a user's TSP account.<br><br>\n**Scopes:** `tsp:write:admin` `tsp:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n",
        "operationId" : "addAUserSTspAccount"
      }
    },
    "/users/{userId}/tsp/settings" : {
      "patch" : {
        "tags" : [ "users", "{user Id}", "tsp" ],
        "summary" : "Set global dial-in URL for a TSP user",
        "description" : "A global dial-in page can provide a list of global access numbers using which audio conferencing can be conducted. By calling this API, you can set the url for the global dial-in page of a user whose Zoom account has TSP and special TSP with third-party audio conferencing options enabled. <p></p>\n**Scopes:**`tsp:write:admin` `tsp:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n",
        "operationId" : "setGlobalDialInUrlForATspUser"
      }
    },
    "/users/{userId}/tsp/{tspId}" : {
      "get" : {
        "tags" : [ "users", "{user Id}", "tsp", "{tsp Id}" ],
        "summary" : "Get a user's TSP account",
        "description" : "Each user can have a maximum of two TSP accounts. Use this API to retrieve details of a specific TSP account enabled for a specific user.<br><br>\n**Scopes:** `tsp:read:admin` `tsp:read`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n",
        "operationId" : "getAUserSTspAccount"
      },
      "delete" : {
        "tags" : [ "users", "{user Id}", "tsp", "{tsp Id}" ],
        "summary" : "Delete a user's TSP account",
        "description" : "Delete a user's TSP account.<br><br>\n**Scopes:** `tsp:write:admin` `tsp:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n",
        "operationId" : "deleteAUserSTspAccount"
      },
      "patch" : {
        "tags" : [ "users", "{user Id}", "tsp", "{tsp Id}" ],
        "summary" : "Update a TSP account",
        "description" : "Update a user's TSP account.<br><br>\n**Scopes:** `tsp:write:admin` `tsp:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`\n",
        "operationId" : "updateATspAccount"
      }
    },
    "/users/{userId}/webinar_templates" : {
      "get" : {
        "tags" : [ "users", "{user Id}" ],
        "summary" : "List webinar templates",
        "description" : "When you schedule a webinar, you can save the settings for that webinar as a template for scheduling future webinars. <br><br>Use this API to list a user's existing [Webinar templates'](https://support.zoom.us/hc/en-us/articles/115001079746-Webinar-Templates) information.\n\n**Prerequisites:**\n* Pro or a higher account with Webinar plan enabled.",
        "operationId" : "listWebinarTemplates"
      }
    },
    "/users/{userId}/webinars" : {
      "get" : {
        "tags" : [ "users", "{user Id}", "webinars" ],
        "summary" : "List webinars",
        "description" : "Zoom users with a [Webinar Plan](https://zoom.us/webinar) have access to creating and managing Webinars. Webinar allows a host to broadcast a Zoom meeting to up to 10,000 attendees.<br> Use this API to list all the webinars that are scheduled by or on-behalf a user (Webinar host).<br><br>\n**Scopes:** `webinar:read:admin` `webinar:read`<br> <br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`\n**Prerequisites:[...]",
        "operationId" : "listWebinars"
      },
      "post" : {
        "tags" : [ "users", "{user Id}", "webinars" ],
        "summary" : "Create a webinar",
        "description" : "Zoom users with a [Webinar Plan](https://zoom.us/webinar) have access to creating and managing Webinars. Webinar allows a host to broadcast a Zoom meeting to up to 10,000 attendees.<br>Use this API to schedule a Webinar for a user (host).<br><br> \n**Scopes:** `webinar:write:admin` `webinar:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n**Prerequisites:**\n* Pro or higher plan with a Webinar Ad[...]",
        "operationId" : "createAWebinar"
      }
    },
    "/webinars/{webinarId}" : {
      "get" : {
        "tags" : [ "webinars/{webinar Id}1" ],
        "summary" : "Get a webinar",
        "description" : "Zoom users with a [Webinar Plan](https://zoom.us/webinar) have access to creating and managing Webinars. Webinar allows a host to broadcast a Zoom meeting to up to 10,000 attendees.<br>Use this API to get details of a scheduled webinar.<br><br>\n**Scopes:** `webinar:read:admin` `webinar:read`<br> \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>**Prerequisites:**\n* Pro or higher plan with a Webinar Add-on.",
        "operationId" : "getAWebinar"
      },
      "delete" : {
        "tags" : [ "webinars/{webinar Id}1" ],
        "summary" : "Delete a webinar",
        "description" : "Delete a Webinar.<br><br>\n**Scopes:** `webinar:write:admin` `webinar:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n**Prerequisites:**<br>\n* Pro or higher plan with a Webinar Add-on.",
        "operationId" : "deleteAWebinar"
      },
      "patch" : {
        "tags" : [ "webinars/{webinar Id}1" ],
        "summary" : "Update a webinar",
        "description" : "Zoom users with a [Webinar Plan](https://zoom.us/webinar) have access to creating and managing Webinars. Webinar allows a host to broadcast a Zoom meeting to up to 10,000 attendees.<br>\nUse this API to make updates to a scheduled Webinar.<br><br>\n**Scopes:** `webinar:write:admin` `webinar:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n**Prerequisites:**<br>\n* Pro or higher plan with a Webina[...]",
        "operationId" : "updateAWebinar"
      }
    },
    "/webinars/{webinarId}/batch_registrants" : {
      "post" : {
        "tags" : [ "webinars/{webinar Id}1" ],
        "summary" : "Perform batch registration",
        "description" : "Use this API to register up to 30 registrants at once for a scheduled webinar that requires [registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-webinar-with-registration). <br>\n\n**Prerequisites:**<br>\n* The webinar host must be a Licensed user.\n* The webinar should be of type `5`, i.e., it should be a scheduled webinar. Other types of webinars are not supported by this API.<br><br>\n**Scope:** `webinar:write`, `webinar:write:admin`<br>\n**[...]",
        "operationId" : "performBatchRegistration"
      }
    },
    "/webinars/{webinarId}/panelists" : {
      "get" : {
        "tags" : [ "webinars/{webinar Id}1", "panelists" ],
        "summary" : "List panelists",
        "description" : "Panelists in a Webinar can view and send video, screen share, annotate, etc and do much more compared to attendees in a Webinar. \n\nUse this API to list all the panelists of a Webinar.<br><br>\n**Scopes:** `webinar:read:admin` `webinar:read`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>\n**Prerequisites:**<br>\n* Pro or a higher plan with [Webinar Add-on](https://zoom.us/webinar).<br> ",
        "operationId" : "listPanelists"
      },
      "post" : {
        "tags" : [ "webinars/{webinar Id}1", "panelists" ],
        "summary" : "Add panelists",
        "description" : "Panelists in a Webinar can view and send video, screen share, annotate, etc and do much more compared to attendees in a webinar.<br>Use this API to [add panelists](https://support.zoom.us/hc/en-us/articles/115005657826-Inviting-Panelists-to-a-Webinar#h_7550d59e-23f5-4703-9e22-e76bded1ed70) to a scheduled webinar.<br><br>\n**Scopes:** `webinar:write:admin` `webinar:write`<br> \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):*[...]",
        "operationId" : "addPanelists"
      },
      "delete" : {
        "tags" : [ "webinars/{webinar Id}1", "panelists" ],
        "summary" : "Remove panelists",
        "description" : "Remove all the panelists from a Webinar.<br>\n**Scopes:** `webinar:write:admin` `webinar:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n**Prerequisites:**<br>\n* Pro or a higher plan with [Webinar Add-on](https://zoom.us/webinar).<br> ",
        "operationId" : "removePanelists"
      }
    },
    "/webinars/{webinarId}/panelists/{panelistId}" : {
      "delete" : {
        "tags" : [ "webinars/{webinar Id}1", "panelists" ],
        "summary" : "Remove a panelist",
        "description" : "[Remove](https://support.zoom.us/hc/en-us/articles/115005657826-Inviting-Panelists-to-a-Webinar#h_de31f237-a91c-4fb2-912b-ecfba8ec5ffb) a single panelist from a webinar.<br> You can retrieve the `panelistId` by calling **List Panelists API**.<br><br>\n**Scopes:** `webinar:write:admin` `webinar:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n\n\n**Prerequisites:**<br>\n* Pro or a higher plan with[...]",
        "operationId" : "removeAPanelist"
      }
    },
    "/webinars/{webinarId}/polls" : {
      "get" : {
        "tags" : [ "webinars/{webinar Id}1", "polls" ],
        "summary" : "List a webinar's polls ",
        "description" : "List all the [polls](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars) of a Webinar.<br><br>\n**Scopes:** `webinar:read:admin` `webinar:read`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n\n",
        "operationId" : "listAWebinarSPolls"
      },
      "post" : {
        "tags" : [ "webinars/{webinar Id}1", "polls" ],
        "summary" : "Create a webinar's poll",
        "description" : "Create a [poll](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars) for a webinar.<br><br>\n**Scopes:** `webinar:write:admin` `webinar:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n\n",
        "operationId" : "createAWebinarSPoll"
      }
    },
    "/webinars/{webinarId}/polls/{pollId}" : {
      "get" : {
        "tags" : [ "webinars/{webinar Id}1", "polls", "{poll Id}" ],
        "summary" : "Get a webinar poll",
        "description" : "Get a webinar's [poll](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars) details.<br><br>\n**Scopes:** `webinar:read:admin` `webinar:read`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n\n",
        "operationId" : "getAWebinarPoll"
      },
      "put" : {
        "tags" : [ "webinars/{webinar Id}1", "polls", "{poll Id}" ],
        "summary" : "Update a webinar poll",
        "description" : "Update a webinar's [poll](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars).<br><br>\n**Scopes:** `webinar:write:admin` `webinar:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n\n",
        "operationId" : "updateAWebinarPoll"
      },
      "delete" : {
        "tags" : [ "webinars/{webinar Id}1", "polls", "{poll Id}" ],
        "summary" : "Delete a webinar poll",
        "description" : "Delete a webinar's [poll](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars).<br><br>\n**Scopes:** `webinar:write:admin` `webinar:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n\n",
        "operationId" : "deleteAWebinarPoll"
      }
    },
    "/webinars/{webinarId}/registrants" : {
      "get" : {
        "tags" : [ "webinars/{webinar Id}1", "registrants1" ],
        "summary" : "List webinar registrants",
        "description" : "Zoom users with a [Webinar Plan](https://zoom.us/webinar) have access to creating and managing Webinars. Webinar allows a host to broadcast a Zoom meeting to up to 10,000 attendees. Scheduling a [Webinar with registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-Webinar-with-Registration) requires your registrants to complete a brief form before receiving the link to join the Webinar.<br>\nUse this API to list all the users that have registered f[...]",
        "operationId" : "listWebinarRegistrants"
      },
      "post" : {
        "tags" : [ "webinars/{webinar Id}1", "registrants1" ],
        "summary" : "Add a webinar registrant",
        "description" : "Zoom users with a [Webinar Plan](https://zoom.us/webinar) have access to creating and managing Webinars. Webinar allows a host to broadcast a Zoom meeting to up to 10,000 attendees. Scheduling a [Webinar with registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-Webinar-with-Registration) requires your registrants to complete a brief form before receiving the link to join the Webinar.<br>Use this API to create and submit the registration of a use[...]",
        "operationId" : "addAWebinarRegistrant"
      }
    },
    "/webinars/{webinarId}/registrants/questions" : {
      "get" : {
        "tags" : [ "webinars/{webinar Id}1", "registrants1", "questions1" ],
        "summary" : "List registration questions",
        "description" : "Scheduling a [Webinar with registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-Webinar-with-Registration) requires your registrants to complete a brief form with fields and questions before they can receive the link to join the Webinar.<br>Use this API to list registration questions and fields that are to be answered by users while registering for a Webinar.<br>\n**Prerequisites:**<br>  \n* Pro or higher plan with a Webinar Add-on.\n**Scopes:**[...]",
        "operationId" : "listRegistrationQuestions1"
      },
      "patch" : {
        "tags" : [ "webinars/{webinar Id}1", "registrants1", "questions1" ],
        "summary" : "Update registration questions",
        "description" : "Scheduling a [Webinar with registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-Webinar-with-Registration) requires your registrants to complete a brief form with fields and questions before they can receive the link to join the Webinar.<br>Use this API to update registration questions and fields of a scheduled Webinar that are to be answered by users while registering for a Webinar.<br><br>\n**Prerequisites:**<br>  \n* Pro or higher plan with a[...]",
        "operationId" : "updateRegistrationQuestions1"
      }
    },
    "/webinars/{webinarId}/registrants/status" : {
      "put" : {
        "tags" : [ "webinars/{webinar Id}1", "registrants1" ],
        "summary" : "Update registrant's status",
        "description" : "Update a webinar registrant's status. Using this API, you can specify whether you want to approve a registration, deny a registration or cancel a previously approved registration.<br><br>\n**Scopes:** `webinar:write:admin` `webinar:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`<br>\n\n",
        "operationId" : "updateRegistrantSStatus1"
      }
    },
    "/webinars/{webinarId}/registrants/{registrantId}" : {
      "get" : {
        "tags" : [ "webinars/{webinar Id}1", "registrants1", "{registrant Id}" ],
        "summary" : "Get a webinar registrant",
        "description" : "Zoom users with a [Webinar Plan](https://zoom.us/webinar) have access to creating and managing Webinars. Webinar allows a host to broadcast a Zoom meeting to up to 10,000 attendees. Scheduling a [Webinar with registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-Webinar-with-Registration) requires your registrants to complete a brief form before receiving the link to join the Webinar.<br>Use this API to get details on a specific user who has regi[...]",
        "operationId" : "getAWebinarRegistrant"
      },
      "delete" : {
        "tags" : [ "webinars/{webinar Id}1", "registrants1", "{registrant Id}" ],
        "summary" : "Delete a webinar registrant",
        "description" : "Delete a webinar registrant.<br><br>\n**Scopes**: `webinar:write:admin` `webinar:write`<br>\n <br>\n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
        "operationId" : "deleteAWebinarRegistrant"
      }
    },
    "/webinars/{webinarId}/status" : {
      "put" : {
        "tags" : [ "webinars/{webinar Id}1" ],
        "summary" : "Update webinar status",
        "description" : "Update a webinar's status. Use this API to end an ongoing webinar.<br><br>\n**Scopes:** `webinar:write:admin` `webinar:write`<br>\n \n **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>\n**Prerequisites:**<br>\n* The account must hold a valid [Webinar plan](https://zoom.us/webinar).",
        "operationId" : "updateWebinarStatus"
      }
    },
    "/webinars/{webinarId}/tracking_sources" : {
      "get" : {
        "tags" : [ "webinars/{webinar Id}1" ],
        "summary" : "Get webinar tracking sources",
        "description" : "[Webinar Registration Tracking Sources](https://support.zoom.us/hc/en-us/articles/360000315683-Webinar-Registration-Source-Tracking) allow you to see where your registrants are coming from if you share the webinar registration page in multiple platforms. You can then use the source tracking to see the number of registrants generated from each platform.<br> Use this API to list information on all the tracking sources of a Webinar.<br>\n**Scopes:** `webinar:read:admin`, `w[...]",
        "operationId" : "getWebinarTrackingSources"
      }
    }
  },
  "components" : {
  }
}